name: RobinMPhotography
favicon: null
layout_spectrum: 1
typography_spectrum: 0.64337
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#3a3a3c'
    - '#f9a583'
    - '#828186'
    - '#c4c4c5'
  brandStrength: 0.1875
  lightness: 0.7272454972844571
  saturation: 0.797219725092873
  rhythmicContrast: 0.6337664278689772
purpose: []
